### ISSUE TITLE
CI/CD Integration...

### ISSUE THREAD

**Issue by rojopolis** [hieven/terraform-visual#1]
This is a cool project!  We currently use Github Actions to automate our TF workflow.  On PR a plan is generated and the PR is updated with the text output of the plan.  It would be neat if we could include a link that would render it with your tool.  Right now it seems like we'd have to post the content of the json plan, but if we could include a URL to a json file (in an S3 bucket for example) in a url query string it should be possible to generate a link directly to a rendered diagram.

**Comment by hieven** [comment]
@rojopolis 
That's a really cool idea! In fact, I'm actively looking for a way to integrate with CI/CD easily as that's the most common use case (who wants to manually generate plan and upload in every commit, right?)

To use URL query string is a good idea but I'm wondering will it become a security issue since the link to your TF state will be public and it does contain a lot of sensitive data 🤔 

Thanks for your feedback anyway, and I'm happy to see how I can make this project more suitable for CI/CD scenario

**Comment by tyronedd** [comment]
My 2 cents here, but I would like the tool to be more of a CLI type tool, where you can input the plan and it generates a static site for you. Like you can do with Jest by running `jest --coverage`. That command generated a static site which I can browse as an artifact inside Gitlab CI.

**Comment by hieven** [comment]
@tyronedd Thanks for your feedback! A CLI tool sounds cool but my initial idea is to provide a backend service which can retrieve TF state from whatever blob storage (e.g. AWS S3)
People can then easily host this service in a secure network. WDYT?

**Comment by ryandharper** [comment]
I'd agree with the original idea @tyronedd had. I'm not sure how some companies may feel about having a tool from github access their terraform state directly, whereas I see the tf.out file and static site generation approach fitting nicely in the pipelies I manage. Hope that helps!

**Comment by hieven** [comment]
@ryandharper thanks for your feedback. I'm curious about by making "generate a static site from tf.out" as a step in your CI pipeline, how do imagine team members to view the results?

**Comment by ryandharper** [comment]
No problem, thanks for putting this together! Most CI/CD tools let you download artifacts, some will even let you view them in the browser. An Artifact is just a file that you have told the CI platform is important. The artifact will exist on an agent (agent being the server that runs the CI jobs) and be defining an Artifact we tell it that the file should be shared by the UI of the CI/CD platform itself.

**Comment by ryandharper** [comment]
In this case you could either present the artifact as a tarball version of the website, with the visual contents of the out file, a webpage or some single file that contains all the content of the site you wish to display. I'm not as good at web technologies as you are otherwise I'd submit a PR myself!

**Comment by hieven** [comment]
@ryandharper thanks for the explanation! However, I still feel to ask people to download static files before they can see the graph is a friction especially this tool can be helpful for PR review but downloading files in every PR manually is a hassle. Maybe there are some common practice to automate this step but I need your knowledge here to find the missing pieces.

On the other hand, let me explain my initial idea more clear to see whether I can get you onboard this one 😄 

Terraform Visual will
1. Provide a Dockerfile containing current work + a backend server
2. Allow you to choose which blob store the backend server talks to and I can provide some default integrations (e.g. AWS S3)

Your team will
1. Host Terraform Visual by using the Dockerfile in your secure network (e.g. behind VPN)
2. Modify your pipeline to upload TF plan to blob store (e.g. AWS S3)
3. Team member can go to the private link and see the results immediately

I guess my major concern is how to provide a seamless experience so developer can view the graph in one click

**Comment by Klintrup** [comment]
Just my 2 cents - I'll be referring to terraform visual as tfvisual here to avoid confusion between terraform visua` and `terraform plan` the command - hope that's ok.

@hieven I think your solution could work, but personally I think it would be easier if tfvisual handled the blob storage.

Expanding on your workflow:
initial setup:
1. (tfvisual) run docker with tfvisual Dockerfile to expose tfvisual via http/https
2. (tfvisual) configure container with the object storage backend (e.g. AWS S3) via environment on K8S/dockerhost
3. (ci) run `terraform plan -out=tfplan.out` to generate tfplan.out
4. (ci) send tfplan.out to tfvisual REST API
5. (tfvisual) read tfplan.out from ci
6. (tfvisual) generate unique filename and write tfplan.out to object storage configured in 2 (e.g. s3a://internal-s3-bucket/tfvisual/dc755557-a683-47c1-8aa9-8af237edadcf.tfout)
7. (tfvisual) return URL as json response to REST API e.g. { "result": { "viewer": "https://tfvisual.internalorg/api/v1/view/dc755557-a683-47c1-8aa9-8af237edadcf" } }
8. (ci) print returned URL as part of CI Run log

This way you keep all communication and configuration of the object storage in one place, so updating the configuration only takes one change, instead of potentially 100's or 1000's of changes in various CI flows to update the upload location.

If you want to pivot to a download result, it would be easy to add a "download": response in the "result" section where the CI flow could then download a tarball or zipfile of the file (though I think it'd be better to generate a single page file with everything included) that could be attached to the output as an artifact like @ryandharper mentioned.

The current webpage with a form can still exist, it would just be a simple static page that use the exposed API to generate the plan, redirecting to the view page.

**Comment by hieven** [comment]
@Klintrup that's exactly what I imagine initially. I might start going to this direction in upcoming days and see how it goes

**Comment by tyronedd** [comment]
@hieven just as an example of what I have in mind, using the Gitlab project:

https://gitlab.com/gitlab-org/gitlab/-/jobs/583906689/artifacts/browse
Artifacts are easily made accessible as a Merge Request widget in Gitlab

if you follow the link above and navigate to `coverage-frontend/lcov-report/index.html` and open `index.html` you can see it Gitlab CI actually exposes a static site which you can browse through.

This is very Gitlab centric, I would think other CI tools have similar capabilities. But this way I have don't have any state I have to push to any Cloud storage and no external API calls have to be made.

**Comment by hieven** [comment]
Hi @tyronedd, sorry for the late reply. I've been really busy at work recently. Thank you for the detailed explanation of how to use artifacts in Gitlab and I like how simple it is to integrate with.

However, my job currently is relying on Drone CI heavily and I don't see same functionality is available there (Also, we're using a relatively old version of Drone CI). In order to keep the momentum, I'd like to continue the direction to a portable Docker image with a secure backend service (more likely I can bring this to my work)

It will be highly appreciated if you could submit a PR for the direction to CLI and artifact approach and I'll be more than happy to keep discussing with you about any details.

Thank you for the suggestion and explanation! 👍

**Comment by hieven** [comment]
Hi @rojopolis @tyronedd @ryandharper @Klintrup,
I've been working on the backend in the past few months and now it's almost ready. [branch:add-backend](https://github.com/hieven/terraform-visual/tree/add-backend).

For the next step, I'd like to provide plugins for your CI/CD pipeline. It will be good to have a chat with each of you respectively to understand more details.

If you'd like to help, please send your email to me (hieven.c@gmail.com). Your contributions are really helpful and I sincerely appreciate it.

**Comment by hieven** [comment]
As I can see more and more people like the idea of CLI tool, it's now available on NPM!
Please refer to https://www.npmjs.com/package/@terraform-visual/cli for more details
And I'd like to get feedback from you 👍

**Comment by ryandharper** [comment]
> Hi @rojopolis @tyronedd @ryandharper @Klintrup,
> I've been working on the backend in the past few months and now it's almost ready. [branch:add-backend](https://github.com/hieven/terraform-visual/tree/add-backend).
> 
> For the next step, I'd like to provide plugins for your CI/CD pipeline. It will be good to have a chat with each of you respectively to understand more details.
> 
> If you'd like to help, please send your email to me ([hieven.c@gmail.com](mailto:hieven.c@gmail.com)). Your contributions are really helpful and I sincerely appreciate it.

Hey @hieven  , a plugin might not be required. I've tried to run the backend branch locally with `yarn` then `npm start`, but have a module error , suggest you update the README in the PR if I'm taking the wrong steps, or perhaps this is some other error 👍  

```
npm start

> terraform-visual@0.0.1 start /Users/rdharper/projects/terraform-visual
> npm run start:backend


> terraform-visual@0.0.1 start:backend /Users/rdharper/projects/terraform-visual
> cd backend && node -r ./tsconfig-paths-bootstrap.js dist/cmd/server/index

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module '/Users/rdharper/projects/terraform-visual/backend/dist/cmd/server/index'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._resolveFilename (/Users/rdharper/projects/terraform-visual/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terraform-visual@0.0.1 start:backend: `cd backend && node -r ./tsconfig-paths-bootstrap.js dist/cmd/server/index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terraform-visual@0.0.1 start:backend script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rdharper/.npm/_logs/2020-07-31T08_42_50_622Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terraform-visual@0.0.1 start: `npm run start:backend`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terraform-visual@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by hieven** [comment]
@ryandharper Indeed, I still need some time to polish the backend branch to make it more user friendly. Meanwhile, would you mind to give the CLI tool a try?

I'd like to get some feedback about
1. How does it look like from user perspective in general?
2. Is the doc clear?
3. Is it good enough for people to integrate it in their CI/CD?

Many thanks for your participation!

**Comment by tyronedd** [comment]
> As I can see more and more people like the idea of CLI tool, it's now available on NPM!
> Please refer to https://www.npmjs.com/package/@terraform-visual/cli for more details
> And I'd like to get feedback from you

Hey @hieven sorry, I forgot to reply to you previously, awesome to see you're making such progress with this!

I followed your docs and combined with my knowledge of Gitlab CI I was able to integrate the tool into an existing PR pipeline in about 30 minutes!

This is how I've done it:

We currently have a `plan` job in the pipeline which runs `terraform plan` and outputs the plan in specific format for another [Gitlab CI Merge Request widget](https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html#artifactsreportsterraform).

I added another step in this job to output the json plan file and upload it as an artifact to be consumed by the next job:

```yaml
terraform/plan:
  extends: .before_script
  stage: plan
  resource_group: staging
  only:
    refs:
      - merge_requests
  artifacts:
    reports:
      terraform: 'src/${JSON_PLAN_FILE}'
    paths:
      - src/tfplan.json
  script: |
    PLAN="merge-request.tfplan"

    terraform plan -out=${PLAN}

    # Convert plan for Merge Request widget
    alias convert_report="jq -r '([.resource_changes[]?.change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"
    terraform show --json $PLAN | convert_report > $JSON_PLAN_FILE
    terraform show --json $PLAN > tfplan.json
```

Then I added another job which use a node image to install the CLI and run the appropriate commands:

```yaml
terraform/visualize:
  extends: .before_script
  image: node:14.7.0-alpine3.10
  stage: visualize
  resource_group: staging
  artifacts:
    name: terraform-visual-report
    expose_as: Terraform Visual
    expire_in: 31d
    when: always
    paths:
      - src/terraform-visual-report/
  only:
    refs:
      - merge_requests
  dependencies:
    - terraform/plan
  script:
    - npm i -g @terraform-visual/cli
    - terraform-visual --plan tfplan.json
```

This is the result:

https://streamable.com/i2bklx

For the short time I used it, I really like it!

The only thing that I don't really like is that I have to add an extra step with a node image loaded, because of the dependency of npm. Ideally, I'd like to be able to use the CLI in the existing plan job, which uses the official terraform image.

**Comment by hieven** [comment]
@tyronedd Thanks for the all the details and especially the video! It's truly amazing to see people integrate with it 👍 

Regarding an additional step and node image, I do agree with you on that. Especially for people who are not familiar with Node.js, it could be a friction.

What about Terraform Visual provides a Docker image with Terraform executable bin and Terraform Visual out of the box?
I takes this idea from the most popular Drone plugin for Terraform, basically I can publish the image with `${TERRAFORM_VISUAL_VER}-${TERRAFORM_VER}` (e.g. `0.1.0-0.12.29`)

In this way, people can freely decide whatever version of Terraform Visual or Terraform they'd like to use and no additional step needed in the pipeline.

Ref: https://hub.docker.com/r/jmccann/drone-terraform/tags

**Comment by hieven** [comment]
Close the issue as we have CLI tool available in NPM for CI/CD integration

**Comment by MPV** [comment]
Anyone that's done this with GitHub Actions yet?
